### ISSUE TITLE
'Dealing Cards' does not test for number of players

### ISSUE THREAD

**Issue by fayesafe** [syntiux/dailyprogrammer#1]
#### OMG, I JUST SAW THIS
Bro, you have one big issue in your dealingcards file. You are not checking whether the number of players actually matches the deck of cards. I'd recommend to also work with exit statements in order to make clear whether the program exited successful or not. 

Another thing is, that you do not 'cast' your input into a String. I am not quite sure if only I got that Problem, but when I entered a number, your program did not work. I needed to add a int() around the input of your program.

Please fix as soon as possible and make sure the failures do not happen again.

KEK KEK KEK KEK KEK KEK

**Comment by syntiux** [comment]
Thanks for your review - I corrected the parts which were not functioning as intended.
